title: video site, Hassan and Associates
author: Syed Hassan Ali
email: webmaster@taxadvisor.ml
url: https://upodesta.gq/callout/
link: https://upodesta.gq/callout/
description: > # this means to ignore newlines until "baseurl:"
  "Video Site, Hassan and Associates, 154/4, West Rampura, WAPDA Road, Dhaka-1219, Bangladesh."

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
#theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
